[build]
  command = "npm run build"
  publish = "dist"

[dev]
  command = "npm run dev"
  port = 3000
  targetPort = 3000
  framework = "vite"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
